### PR TITLE
Replace ts() to E::ts()

### PR DESCRIPTION
**Pull request by lucky091588**

### CODE REVIEW

**Comment by lucky091588** [comment]
I need help testing the changes since I don't know where to check it on the browser.

**Comment by twomice** [comment]
Oops, sorry @lucky091588 I forgot to mention that we also don't want to modify files that are PHP overrides of CiviCRM core files, which in this case includes CRM/Contribute/Form/ContributionBase.php. Please revert changes in that file and update the PR. Thanks.

**Comment by lucky091588** [comment]
@twomice I reverted the changes on the overwritten core file.

**Comment by twomice** [comment]
Merged, thanks @lucky091588

**Pull request merged**
